trigger:
- master

pool:
  name: Default

variables:
  buildConfiguration: 'Release'
  projectPath: 'StringLibrary/StringLibrary.csproj'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate to Azure Artifacts'

- script: dotnet restore
  displayName: 'Restore'

- script: dotnet build $(projectPath) --configuration $(buildConfiguration)
  displayName: 'Build'

- script: dotnet pack $(projectPath) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack NuGet package'

- task: NuGetCommand@2
  displayName: 'Push package to Azure Artifacts Feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;!$(Build.ArtifactStagingDirectory)/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'ClassLibraryProjects-Lab4-Q1/lab4q1feed'
    allowPackageConflicts: true
